mysite/urls.py
# Django site URLs, for 'mysite' project.  Django v1.5
# SEE http://docs.djangoproject.com/en/dev/topics/http/urls/

from django.conf.urls import patterns, url, include

from django.views.generic import TemplateView
#from django.views.generic.simple import direct_to_template

from django.views.generic import DetailView, ListView
from polls.models import Poll

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

#  url( regex, view, [kwargs], [name] )

urlpatterns = patterns('',
    url(r'^polls/', include('polls.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^contact/thanks/', 'simplecontact.views.thanks'),
    url(r'^contact/', 'simplecontact.views.contact'),
    
#   url(r'^basic/$', direct_to_template, {'template': 'todos/basic.html'}),
    url(r'^basic/$', TemplateView.as_view(template_name='todos/basic.html')),

    
#   url(r'^api/', include('mysite.api.urls', 'mysite.piston_testapp.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    )

mysite/simplecontact/models.py
#from django.db import models

# Create your models here.

from django import forms
from django.forms.widgets import Textarea 

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=Textarea())
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

mysite/templates/contacts/contacts.html
{% block fulltitle %}Contact me!{% block title %}{% endblock %}{% endblock %}

{% block header %}
<h3> header, of course</h3>
{% endblock %}

{% block extrahead %}
{% endblock %}

{% block content-wrap %}
        <div id="contact_wrap">

        <div id="contact" class="clearfix">
            <div id="c_form">
                <br /><br />
                <form name="theform" action="." method="post" id="theform">{% csrf_token %}
                    <div id="subject_sender">
                        <label id="id_subject">Subject:</label>
                        <input type="text" name="subject" value="" id="Subject" />
                        <label id="id_sender">Sender email:</label>
                        <input type="text" name="sender" value="" id="Sender" />
                    </div>

                    <div id="message">
                        <label id="id_message">Message:</label>
                        <textarea name="message" rows="8" cols="44"></textarea>
                    </div>

                    <div id="submit">
                        <input type="submit" onclick="YY_checkform('theform','name','#q','0','Field \'name\' is empty.','Email','#S','2','Field \'Email\' appears not to be valid.','message','2','1','Field \'message\' is empty.');return document.MM_returnValue" />
                    </div>

                    <input class="hidden" type="hidden" name="cc_to_myself" value="1" id="CC_to_myself" />
                </form>

            </div><!-- end c_form -->
        </div><!-- end contact -->

    </div><!-- end contact_wrap -->

{% endblock %}

mysite/templates/contacts/thanks.html
{% block billboard %}Services{% endblock %}
{% block title %}Services{% endblock %}

{% block header %}
<h3> header of course</h3>
{% endblock %}

{% block content %}
<h3>Contact Information</h3>

<p>Thank you for contacting us.</p>

<p>We will attempt to get back to you within 2 Light Years</p>

{% endblock %}